#
# root-level Cargo.toml for monorepo
#
# documentation:
# - https://doc.rust-lang.org/cargo/reference/workspaces.html

[workspace]
members = [
    "ripit-cli",
]
resolver = "3"

[workspace.dependencies]
async-trait = "0.1.92"
atty = "0.2.0"
chrono = "0.4.45"
clap = "4.6.0"
csv = "1.4.0"
dialoguer = "0.12.0"
enum_primitive = "0.1.0"
env_logger = "0.11.0"
exitcode = "1.1.0"
futures = "0.3.0"
indicatif = "0.18.0"
indicatif-log-bridge = "0.2.3"
itertools = "0.15.0"
log = "0.4.0"
makemkv = { path = "libs/makemkv" }
num = "0.4.0"
phf = "0.14.0"
range = "1.0.0"
regex = "1.12.0"
ripit = { path = "libs/ripit" }
serde = "1.0.0"
serde_yaml = "0.9.0"
speedate = "0.17.0"
strum_macros = "0.28.0"
tokio = "1.52.0"
which = "8.0.0"
wild = "2.2.1"
winapi = "0.3.0"

[workspace.package]
authors = [
    "Feeph Aifeimei"
]
license-file = "LICENSE"
rust-version = "1.91"
