[package]
name = "makemkvcon"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
csv = "1.4.0"
enum_primitive = "0.1.1"
futures = "0.3.32"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
log = { version = "0.4.29", features = ["serde", "std"] }
num = "0.4.3"
regex = "1.12.3"
tokio = { version = "1.52.1", features = ["process", "io-util"] }
strum_macros = "0.28.0"
itertools = "0.14.0"
speedate = "0.17.0"
