[package]
authors = { workspace = true }
edition = "2024"
license-file = { workspace = true }
name = "ripit-cli"
rust-version = { workspace = true }
version = "0.1.0"

[dependencies]
atty = { workspace = true }
clap = { features = ["derive", "env"], workspace = true }
dialoguer = { workspace = true }
env_logger = { workspace = true }
exitcode = { workspace = true }
futures.workspace = true
indicatif = { workspace = true, features = ["rayon"] }
indicatif-log-bridge = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
makemkv = { workspace = true }
range = { workspace = true }
regex = { workspace = true }
ripit = { workspace = true }
serde = { features = ["derive", "std"], workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
which = { workspace = true }
