[package]
authors = { workspace = true }
edition = "2024"
license-file = { workspace = true }
name = "makemkv"
rust-version = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
enum_primitive = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
num = { workspace = true }
tokio = { features = ["io-util", "process", "rt", "rt-multi-thread", "sync", "time", "macros"], workspace = true }
regex = { workspace = true }
serde = { features = ["derive", "std"], workspace = true }
strum_macros = { workspace = true }
itertools = { workspace = true }
speedate = { workspace = true }
