[package]
authors = { workspace = true }
edition = "2024"
license-file = { workspace = true }
name = "ripit"
rust-version = { workspace = true }
version = "0.1.0"

[dependencies]
chrono = { workspace = true }
log = { workspace = true }
makemkv = { workspace = true }
phf = { features = ["macros"], workspace = true }
regex = { workspace = true }
serde = { features = ["derive", "std"], workspace = true }
serde_yaml = { workspace = true }
winapi = { features = ["fileapi", "winbase"], workspace = true }
