---
#
# release-please GitHub Action
#
# documentation:
# - https://github.com/googleapis/release-please-action

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7  # v5.0.0
        with:
          # release-please requires a separate token if it should trigger
          # other actions, see the following link for details:
          # https://github.com/googleapis/release-please-action#other-actions-on-release-please-prs
          # token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .github/release-please-manifest.json
